server:
  port: 8081     

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mobility_userdb
    username: postgres
    password: test123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
