server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mobility_userdb
    username: postgres
    password: test123
  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: postgres
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
